### ISSUE TITLE
ADD ccf release folder v1.4 in preparation for 5th release files

### ISSUE THREAD

**Issue by emquardokus** [hubmapconsortium/ccf-releases#39]
@bherr2 would you ADD ccf release folder v1.4 in preparation for 5th release files?
I'd like to get started on preparing markdown files.
Thank-you

**Comment by bherr2** [comment]
Sure. I added a new PR #40 which is the v1.4 branch here: <https://github.com/hubmapconsortium/ccf-releases/tree/v1.4>. Feel free to start adding to this branch as needed.
